# Generated by Django 3.0.5 on 2020-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=models.ImageField(upload_to='accounts_img')),
        ),
    ]
