# Generated by Django 3.0.5 on 2020-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='goal',
            field=models.CharField(choices=[('WEIGHT', 'Lose Weight'), ('TRIM', 'Get Lean'), ('TRAIN', 'Improve Performance'), ('GAIN', 'Muscle Gains')], max_length=10),
        ),
    ]
