# Generated by Django 3.0.5 on 2020-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200409_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default=1, upload_to='main_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
