# Generated by Django 3.0.5 on 2020-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200409_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Get Lean', 'Get Lean'), ('Improve Performance', 'Improve Performance'), ('Muscle Gains', 'Muscle Gains')], max_length=50),
        ),
    ]
