# Generated by Django 3.0.5 on 2020-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200412_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.TextField(),
        ),
    ]
